### ISSUE TITLE
Use Windows line endings in changelog files.

### ISSUE THREAD

**Issue by apigram** [switchtrue/JIRAChangelogBuilder#12]
Generated changelog files are currently using Unix line endings, meaning opening a .txt changelog file using a Windows program like Notepad will not display the changelog in a neat format.

It would be ideal to use windows line endings (CR/LF) so that such files can be opened in Notepad and display a neatly formatted changelog.

**Comment by switchtrue** [comment]
This would be best suited to another optional flag of "--eol-style" that can accept the following values:
- "native" (default if not specified)
- "CRLF" (windows)
- "LF" (*nix) 

You'll need to do something clever with this as its now template based the template is already going to have certain line endings. If the template was written with *nix line endings but we've specified "--eol-style CRLF" then it should it normalise the entire file (i.e. any boiler plate that actually in the template)? Probably, yes.

I guess this means that if --eol-style native or its not specified then do nothing. If its CRLF or LF then normalize all white space in the template and write.

**Comment by apigram** [comment]
Fixed in line-endings branch. Does not alter template file; only the generated changelog.

**Comment by apigram** [comment]
Mike, even though you said that the NATIVE line ending flag should do nothing, what about the test case where someone has copied a template between different computer systems eg. UNIX to Windows? Wouldn't we want to normalise newlines to the method used by the system on which this tool runs rather than matching the template source formatting?

I have included code to handle the above test case.

**Comment by switchtrue** [comment]
Agreed, well spotted.
