### ISSUE TITLE
Consider providing the compiled jar

### ISSUE THREAD

**Issue by marcospassos** [switchtrue/JIRAChangelogBuilder#16]
First of all, congratulations for this awesome project. We use successfully in our CI server.

I would like to suggest provide the latest compiled version so that we can download automatically every time we generate the changelog.

**Comment by switchtrue** [comment]
Hi Marcos,

The compiled jars for each version are available on the "Releases" tab in GitHub and you get to the latest build via: https://github.com/mleonard87/JIRAChangelogBuilder/releases/latest. However at the moment there is no direct download link of the latest version.

Alternatively you could pull the latest version of the source and use maven to build it each time. Instructions are in the "Compilation" section of the readme.

We will investigate adding a direct download link at a future date.

Thanks, Mike.
