### ISSUE TITLE
Ability to pass variables to template

### ISSUE THREAD

**Issue by marcospassos** [switchtrue/JIRAChangelogBuilder#25]
Sometimes is necessary to pass some dynamic data to be used in changelog's template. Passing parameters in the command seems a good way to achieve that (only scalar values).

`jira-chagelog-builder ... foo=1 bar=http://acme.com`

**Comment by switchtrue** [comment]
I doubt we will implement a feature to pass arbitrary flags as this will make the parsing of the command line arguments less robust.

However, #15 proposes a change to allow environment variable to be used in the template. So when this is implemented (sorry no time frame at the moment) you could easily set an environment variable of the dynamic item you want.

In the mean time you could have a step in your build process that dynamically generates the template for you using whatever variables you need.
