### ISSUE TITLE
Hangs when complete

### ISSUE THREAD

**Issue by displaced** [switchtrue/JIRAChangelogBuilder#28]
Hi,

Firstly, thanks for this -- it's exactly what we've been after!

One issue we're seeing which makes this impractical to use in a continuous integration system is that it appears to hang when complete.  I've tried this on both a Linux and a Windows system.  With debugging enabled, it gets to the 'Done - Success!' line... but then requires a Ctrl+C to end.

Unfortunately, this causes the CI build to hang -- any help appreciated!

Thanks,
Chris

**Comment by displaced** [comment]
Ok -- I grabbed the source and added a System.exit(0) after the 'Success' log statement and this has solved the problem.  When I'm at a machine with git installed, I'll do a PR if wanted.

Cheers,
Chris

**Comment by switchtrue** [comment]
I had a hunch it would be something along those lines. I'd be happy to accept a pull request. Cheers.

**Comment by switchtrue** [comment]
Fixed in jira-changelog-builder-1.06.1.
