### ISSUE TITLE
Template based changelogs

### ISSUE THREAD

**Issue by switchtrue** [switchtrue/JIRAChangelogBuilder#3]
The output format of the changelog is currently hardcoded. It would be nice if it could also produce XML/HTML/etc. Consider using a mustache-like (http://mustache.github.io/) templating format. Pass the template to use as a command line flag so that the same changelog builder jar can be used in different circumstances. 
Could have a default template of "default.tmpl" or similar.

**Comment by apigram** [comment]
Enhancement has been added to master branch.
