### ISSUE TITLE
Cache policy

### ISSUE THREAD

**Issue by Pierre-Do** [switchtrue/JIRAChangelogBuilder#6]
If a JIRA is failed and is now part of another release, the previous release's item cached still has this issue listed.

It would be great to update the cache policy to invalidate a cached element if one of the JIRA listed is updated.

**Comment by switchtrue** [comment]
There is no real way to determine this without re-querying all the data over HTTP which is exactly what the cache is trying to avoid.

There are, however, a couple of steps you could try to mitigate the issue:
- Don't use the cache, the constant refreshing over HTTP isn't too slow you just need to omit the `--object-cache-path` flag.
- Manually remove the cache object for the version you know is wrong. See https://github.com/mleonard87/JIRAChangelogBuilder/blob/master/README.md#managing-the-cache for further information.
- Modify you JIRA workflow and use some of the advance JQL functions such as the "WAS IN" operator to more carefully control under which conditions your issues are selected. (https://confluence.atlassian.com/display/JIRA/Advanced+Searching#AdvancedSearching-WASIN)
