### ISSUE TITLE
Element ordering when multiple versions have been released the same day.

### ISSUE THREAD

**Issue by Pierre-Do** [switchtrue/JIRAChangelogBuilder#7]
If multiple versions have the same release dates, those versions will be sorted by version number ascending instead of descending.

Sample output:

11-06-2013  XXX-2.9.006
Bug fix release for XXX-2.9.000
[...]

07-06-2013  XXX-2.9.003
Bug fix release for XXX-2.9.000
[...]

07-06-2013  XXX-2.9.004
Bug fix release for XXX-2.9.000
[...]

07-06-2013  XXX-2.9.005
Bug fix release for XXX-2.9.000
[...]

06-06-2013  XXX-2.9.002
Bug fix release for XXX-2.9.000
[...]

05-06-2013  SEWPAC-2.9.001
Bug fix release for SEWPAC-2.9.000
[...]

**Comment by apigram** [comment]
Fixed as part of the changelogsort branch. Only required adding a secondary sorting condition based on version number when the version release dates match.
